apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vdg5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vdg5
    app.kubernetes.io/part-of: tkrw-pr712-0075-0038-app
  name: devfile-sample-vdg5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vdg5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vdg5
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-vdg5@sha256:d747b60ed16e2108db89bb2c8f1fdc808641068181b6e41787d82e13f116fa59
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
